// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: proto/tag/tag.proto

package tagpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagName       string                 `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_proto_tag_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *Tag) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Tag) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagName       string                 `protobuf:"bytes,1,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_proto_tag_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTagRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

type CreateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *Tag                   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagResponse) Reset() {
	*x = CreateTagResponse{}
	mi := &file_proto_tag_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResponse) ProtoMessage() {}

func (x *CreateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResponse.ProtoReflect.Descriptor instead.
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTagResponse) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type FindTagByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTagByIDRequest) Reset() {
	*x = FindTagByIDRequest{}
	mi := &file_proto_tag_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTagByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTagByIDRequest) ProtoMessage() {}

func (x *FindTagByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTagByIDRequest.ProtoReflect.Descriptor instead.
func (*FindTagByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{3}
}

func (x *FindTagByIDRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindTagByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *Tag                   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTagByIDResponse) Reset() {
	*x = FindTagByIDResponse{}
	mi := &file_proto_tag_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTagByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTagByIDResponse) ProtoMessage() {}

func (x *FindTagByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTagByIDResponse.ProtoReflect.Descriptor instead.
func (*FindTagByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{4}
}

func (x *FindTagByIDResponse) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type FindAllTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTagsRequest) Reset() {
	*x = FindAllTagsRequest{}
	mi := &file_proto_tag_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTagsRequest) ProtoMessage() {}

func (x *FindAllTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTagsRequest.ProtoReflect.Descriptor instead.
func (*FindAllTagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{5}
}

type FindAllTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTagsResponse) Reset() {
	*x = FindAllTagsResponse{}
	mi := &file_proto_tag_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTagsResponse) ProtoMessage() {}

func (x *FindAllTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTagsResponse.ProtoReflect.Descriptor instead.
func (*FindAllTagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PatchTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagName       string                 `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchTagRequest) Reset() {
	*x = PatchTagRequest{}
	mi := &file_proto_tag_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchTagRequest) ProtoMessage() {}

func (x *PatchTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchTagRequest.ProtoReflect.Descriptor instead.
func (*PatchTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{7}
}

func (x *PatchTagRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchTagRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

type PatchTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *Tag                   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchTagResponse) Reset() {
	*x = PatchTagResponse{}
	mi := &file_proto_tag_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchTagResponse) ProtoMessage() {}

func (x *PatchTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchTagResponse.ProtoReflect.Descriptor instead.
func (*PatchTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{8}
}

func (x *PatchTagResponse) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_proto_tag_tag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTagRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_proto_tag_tag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_tag_tag_proto protoreflect.FileDescriptor

const file_proto_tag_tag_proto_rawDesc = "" +
	"\n" +
	"\x13proto/tag/tag.proto\x12\x03tag\"n\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\btag_name\x18\x02 \x01(\tR\atagName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"-\n" +
	"\x10CreateTagRequest\x12\x19\n" +
	"\btag_name\x18\x01 \x01(\tR\atagName\"/\n" +
	"\x11CreateTagResponse\x12\x1a\n" +
	"\x03tag\x18\x01 \x01(\v2\b.tag.TagR\x03tag\"$\n" +
	"\x12FindTagByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"1\n" +
	"\x13FindTagByIDResponse\x12\x1a\n" +
	"\x03tag\x18\x01 \x01(\v2\b.tag.TagR\x03tag\"\x14\n" +
	"\x12FindAllTagsRequest\"3\n" +
	"\x13FindAllTagsResponse\x12\x1c\n" +
	"\x04tags\x18\x01 \x03(\v2\b.tag.TagR\x04tags\"<\n" +
	"\x0fPatchTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\btag_name\x18\x02 \x01(\tR\atagName\".\n" +
	"\x10PatchTagResponse\x12\x1a\n" +
	"\x03tag\x18\x01 \x01(\v2\b.tag.TagR\x03tag\"\"\n" +
	"\x10DeleteTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"-\n" +
	"\x11DeleteTagResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc1\x02\n" +
	"\n" +
	"TagService\x12:\n" +
	"\tCreateTag\x12\x15.tag.CreateTagRequest\x1a\x16.tag.CreateTagResponse\x12@\n" +
	"\vFindTagByID\x12\x17.tag.FindTagByIDRequest\x1a\x18.tag.FindTagByIDResponse\x12@\n" +
	"\vFindAllTags\x12\x17.tag.FindAllTagsRequest\x1a\x18.tag.FindAllTagsResponse\x127\n" +
	"\bPatchTag\x12\x14.tag.PatchTagRequest\x1a\x15.tag.PatchTagResponse\x12:\n" +
	"\tDeleteTag\x12\x15.tag.DeleteTagRequest\x1a\x16.tag.DeleteTagResponseB,Z*github.com/MingPV/EventService/proto/tagpbb\x06proto3"

var (
	file_proto_tag_tag_proto_rawDescOnce sync.Once
	file_proto_tag_tag_proto_rawDescData []byte
)

func file_proto_tag_tag_proto_rawDescGZIP() []byte {
	file_proto_tag_tag_proto_rawDescOnce.Do(func() {
		file_proto_tag_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tag_tag_proto_rawDesc), len(file_proto_tag_tag_proto_rawDesc)))
	})
	return file_proto_tag_tag_proto_rawDescData
}

var file_proto_tag_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_tag_tag_proto_goTypes = []any{
	(*Tag)(nil),                 // 0: tag.Tag
	(*CreateTagRequest)(nil),    // 1: tag.CreateTagRequest
	(*CreateTagResponse)(nil),   // 2: tag.CreateTagResponse
	(*FindTagByIDRequest)(nil),  // 3: tag.FindTagByIDRequest
	(*FindTagByIDResponse)(nil), // 4: tag.FindTagByIDResponse
	(*FindAllTagsRequest)(nil),  // 5: tag.FindAllTagsRequest
	(*FindAllTagsResponse)(nil), // 6: tag.FindAllTagsResponse
	(*PatchTagRequest)(nil),     // 7: tag.PatchTagRequest
	(*PatchTagResponse)(nil),    // 8: tag.PatchTagResponse
	(*DeleteTagRequest)(nil),    // 9: tag.DeleteTagRequest
	(*DeleteTagResponse)(nil),   // 10: tag.DeleteTagResponse
}
var file_proto_tag_tag_proto_depIdxs = []int32{
	0,  // 0: tag.CreateTagResponse.tag:type_name -> tag.Tag
	0,  // 1: tag.FindTagByIDResponse.tag:type_name -> tag.Tag
	0,  // 2: tag.FindAllTagsResponse.tags:type_name -> tag.Tag
	0,  // 3: tag.PatchTagResponse.tag:type_name -> tag.Tag
	1,  // 4: tag.TagService.CreateTag:input_type -> tag.CreateTagRequest
	3,  // 5: tag.TagService.FindTagByID:input_type -> tag.FindTagByIDRequest
	5,  // 6: tag.TagService.FindAllTags:input_type -> tag.FindAllTagsRequest
	7,  // 7: tag.TagService.PatchTag:input_type -> tag.PatchTagRequest
	9,  // 8: tag.TagService.DeleteTag:input_type -> tag.DeleteTagRequest
	2,  // 9: tag.TagService.CreateTag:output_type -> tag.CreateTagResponse
	4,  // 10: tag.TagService.FindTagByID:output_type -> tag.FindTagByIDResponse
	6,  // 11: tag.TagService.FindAllTags:output_type -> tag.FindAllTagsResponse
	8,  // 12: tag.TagService.PatchTag:output_type -> tag.PatchTagResponse
	10, // 13: tag.TagService.DeleteTag:output_type -> tag.DeleteTagResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_tag_tag_proto_init() }
func file_proto_tag_tag_proto_init() {
	if File_proto_tag_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tag_tag_proto_rawDesc), len(file_proto_tag_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tag_tag_proto_goTypes,
		DependencyIndexes: file_proto_tag_tag_proto_depIdxs,
		MessageInfos:      file_proto_tag_tag_proto_msgTypes,
	}.Build()
	File_proto_tag_tag_proto = out.File
	file_proto_tag_tag_proto_goTypes = nil
	file_proto_tag_tag_proto_depIdxs = nil
}
