// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/eventtag/eventtag.proto

package eventtag_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId         uint32                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTag) Reset() {
	*x = EventTag{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTag) ProtoMessage() {}

func (x *EventTag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTag.ProtoReflect.Descriptor instead.
func (*EventTag) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{0}
}

func (x *EventTag) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventTag) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *EventTag) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EventTag) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateEventTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId         uint32                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventTagRequest) Reset() {
	*x = CreateEventTagRequest{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventTagRequest) ProtoMessage() {}

func (x *CreateEventTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventTagRequest.ProtoReflect.Descriptor instead.
func (*CreateEventTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventTagRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateEventTagRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type CreateEventTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTag      *EventTag              `protobuf:"bytes,1,opt,name=event_tag,json=eventTag,proto3" json:"event_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventTagResponse) Reset() {
	*x = CreateEventTagResponse{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventTagResponse) ProtoMessage() {}

func (x *CreateEventTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventTagResponse.ProtoReflect.Descriptor instead.
func (*CreateEventTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventTagResponse) GetEventTag() *EventTag {
	if x != nil {
		return x.EventTag
	}
	return nil
}

type FindByEventAndTagIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId         uint32                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByEventAndTagIDRequest) Reset() {
	*x = FindByEventAndTagIDRequest{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByEventAndTagIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEventAndTagIDRequest) ProtoMessage() {}

func (x *FindByEventAndTagIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEventAndTagIDRequest.ProtoReflect.Descriptor instead.
func (*FindByEventAndTagIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{3}
}

func (x *FindByEventAndTagIDRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *FindByEventAndTagIDRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type FindByEventAndTagIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTag      *EventTag              `protobuf:"bytes,1,opt,name=event_tag,json=eventTag,proto3" json:"event_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByEventAndTagIDResponse) Reset() {
	*x = FindByEventAndTagIDResponse{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByEventAndTagIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEventAndTagIDResponse) ProtoMessage() {}

func (x *FindByEventAndTagIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEventAndTagIDResponse.ProtoReflect.Descriptor instead.
func (*FindByEventAndTagIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{4}
}

func (x *FindByEventAndTagIDResponse) GetEventTag() *EventTag {
	if x != nil {
		return x.EventTag
	}
	return nil
}

type FindByEventIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByEventIDRequest) Reset() {
	*x = FindByEventIDRequest{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByEventIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEventIDRequest) ProtoMessage() {}

func (x *FindByEventIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEventIDRequest.ProtoReflect.Descriptor instead.
func (*FindByEventIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{5}
}

func (x *FindByEventIDRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type FindByEventIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTags     []*EventTag            `protobuf:"bytes,1,rep,name=event_tags,json=eventTags,proto3" json:"event_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByEventIDResponse) Reset() {
	*x = FindByEventIDResponse{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByEventIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEventIDResponse) ProtoMessage() {}

func (x *FindByEventIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEventIDResponse.ProtoReflect.Descriptor instead.
func (*FindByEventIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{6}
}

func (x *FindByEventIDResponse) GetEventTags() []*EventTag {
	if x != nil {
		return x.EventTags
	}
	return nil
}

type FindByTagIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         uint32                 `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByTagIDRequest) Reset() {
	*x = FindByTagIDRequest{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByTagIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByTagIDRequest) ProtoMessage() {}

func (x *FindByTagIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByTagIDRequest.ProtoReflect.Descriptor instead.
func (*FindByTagIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{7}
}

func (x *FindByTagIDRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type FindByTagIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTags     []*EventTag            `protobuf:"bytes,1,rep,name=event_tags,json=eventTags,proto3" json:"event_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByTagIDResponse) Reset() {
	*x = FindByTagIDResponse{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByTagIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByTagIDResponse) ProtoMessage() {}

func (x *FindByTagIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByTagIDResponse.ProtoReflect.Descriptor instead.
func (*FindByTagIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{8}
}

func (x *FindByTagIDResponse) GetEventTags() []*EventTag {
	if x != nil {
		return x.EventTags
	}
	return nil
}

type FindAllEventTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEventTagsRequest) Reset() {
	*x = FindAllEventTagsRequest{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEventTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEventTagsRequest) ProtoMessage() {}

func (x *FindAllEventTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEventTagsRequest.ProtoReflect.Descriptor instead.
func (*FindAllEventTagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{9}
}

type FindAllEventTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTags     []*EventTag            `protobuf:"bytes,1,rep,name=event_tags,json=eventTags,proto3" json:"event_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEventTagsResponse) Reset() {
	*x = FindAllEventTagsResponse{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEventTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEventTagsResponse) ProtoMessage() {}

func (x *FindAllEventTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEventTagsResponse.ProtoReflect.Descriptor instead.
func (*FindAllEventTagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{10}
}

func (x *FindAllEventTagsResponse) GetEventTags() []*EventTag {
	if x != nil {
		return x.EventTags
	}
	return nil
}

type DeleteEventTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId         uint32                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventTagRequest) Reset() {
	*x = DeleteEventTagRequest{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventTagRequest) ProtoMessage() {}

func (x *DeleteEventTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEventTagRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *DeleteEventTagRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type DeleteEventTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventTagResponse) Reset() {
	*x = DeleteEventTagResponse{}
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventTagResponse) ProtoMessage() {}

func (x *DeleteEventTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventtag_eventtag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventtag_eventtag_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteEventTagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_eventtag_eventtag_proto protoreflect.FileDescriptor

const file_proto_eventtag_eventtag_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/eventtag/eventtag.proto\x12\beventtag\"z\n" +
	"\bEventTag\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\rR\x05tagId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"I\n" +
	"\x15CreateEventTagRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\rR\x05tagId\"I\n" +
	"\x16CreateEventTagResponse\x12/\n" +
	"\tevent_tag\x18\x01 \x01(\v2\x12.eventtag.EventTagR\beventTag\"N\n" +
	"\x1aFindByEventAndTagIDRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\rR\x05tagId\"N\n" +
	"\x1bFindByEventAndTagIDResponse\x12/\n" +
	"\tevent_tag\x18\x01 \x01(\v2\x12.eventtag.EventTagR\beventTag\"1\n" +
	"\x14FindByEventIDRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\"J\n" +
	"\x15FindByEventIDResponse\x121\n" +
	"\n" +
	"event_tags\x18\x01 \x03(\v2\x12.eventtag.EventTagR\teventTags\"+\n" +
	"\x12FindByTagIDRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\rR\x05tagId\"H\n" +
	"\x13FindByTagIDResponse\x121\n" +
	"\n" +
	"event_tags\x18\x01 \x03(\v2\x12.eventtag.EventTagR\teventTags\"\x19\n" +
	"\x17FindAllEventTagsRequest\"M\n" +
	"\x18FindAllEventTagsResponse\x121\n" +
	"\n" +
	"event_tags\x18\x01 \x03(\v2\x12.eventtag.EventTagR\teventTags\"I\n" +
	"\x15DeleteEventTagRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\rR\x05tagId\"2\n" +
	"\x16DeleteEventTagResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x98\x04\n" +
	"\x0fEventTagService\x12S\n" +
	"\x0eCreateEventTag\x12\x1f.eventtag.CreateEventTagRequest\x1a .eventtag.CreateEventTagResponse\x12b\n" +
	"\x13FindByEventAndTagID\x12$.eventtag.FindByEventAndTagIDRequest\x1a%.eventtag.FindByEventAndTagIDResponse\x12P\n" +
	"\rFindByEventID\x12\x1e.eventtag.FindByEventIDRequest\x1a\x1f.eventtag.FindByEventIDResponse\x12J\n" +
	"\vFindByTagID\x12\x1c.eventtag.FindByTagIDRequest\x1a\x1d.eventtag.FindByTagIDResponse\x12Y\n" +
	"\x10FindAllEventTags\x12!.eventtag.FindAllEventTagsRequest\x1a\".eventtag.FindAllEventTagsResponse\x12S\n" +
	"\x0eDeleteEventTag\x12\x1f.eventtag.DeleteEventTagRequest\x1a .eventtag.DeleteEventTagResponseB2Z0github.com/MingPV/EventService/proto/eventtag_pbb\x06proto3"

var (
	file_proto_eventtag_eventtag_proto_rawDescOnce sync.Once
	file_proto_eventtag_eventtag_proto_rawDescData []byte
)

func file_proto_eventtag_eventtag_proto_rawDescGZIP() []byte {
	file_proto_eventtag_eventtag_proto_rawDescOnce.Do(func() {
		file_proto_eventtag_eventtag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_eventtag_eventtag_proto_rawDesc), len(file_proto_eventtag_eventtag_proto_rawDesc)))
	})
	return file_proto_eventtag_eventtag_proto_rawDescData
}

var file_proto_eventtag_eventtag_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_eventtag_eventtag_proto_goTypes = []any{
	(*EventTag)(nil),                    // 0: eventtag.EventTag
	(*CreateEventTagRequest)(nil),       // 1: eventtag.CreateEventTagRequest
	(*CreateEventTagResponse)(nil),      // 2: eventtag.CreateEventTagResponse
	(*FindByEventAndTagIDRequest)(nil),  // 3: eventtag.FindByEventAndTagIDRequest
	(*FindByEventAndTagIDResponse)(nil), // 4: eventtag.FindByEventAndTagIDResponse
	(*FindByEventIDRequest)(nil),        // 5: eventtag.FindByEventIDRequest
	(*FindByEventIDResponse)(nil),       // 6: eventtag.FindByEventIDResponse
	(*FindByTagIDRequest)(nil),          // 7: eventtag.FindByTagIDRequest
	(*FindByTagIDResponse)(nil),         // 8: eventtag.FindByTagIDResponse
	(*FindAllEventTagsRequest)(nil),     // 9: eventtag.FindAllEventTagsRequest
	(*FindAllEventTagsResponse)(nil),    // 10: eventtag.FindAllEventTagsResponse
	(*DeleteEventTagRequest)(nil),       // 11: eventtag.DeleteEventTagRequest
	(*DeleteEventTagResponse)(nil),      // 12: eventtag.DeleteEventTagResponse
}
var file_proto_eventtag_eventtag_proto_depIdxs = []int32{
	0,  // 0: eventtag.CreateEventTagResponse.event_tag:type_name -> eventtag.EventTag
	0,  // 1: eventtag.FindByEventAndTagIDResponse.event_tag:type_name -> eventtag.EventTag
	0,  // 2: eventtag.FindByEventIDResponse.event_tags:type_name -> eventtag.EventTag
	0,  // 3: eventtag.FindByTagIDResponse.event_tags:type_name -> eventtag.EventTag
	0,  // 4: eventtag.FindAllEventTagsResponse.event_tags:type_name -> eventtag.EventTag
	1,  // 5: eventtag.EventTagService.CreateEventTag:input_type -> eventtag.CreateEventTagRequest
	3,  // 6: eventtag.EventTagService.FindByEventAndTagID:input_type -> eventtag.FindByEventAndTagIDRequest
	5,  // 7: eventtag.EventTagService.FindByEventID:input_type -> eventtag.FindByEventIDRequest
	7,  // 8: eventtag.EventTagService.FindByTagID:input_type -> eventtag.FindByTagIDRequest
	9,  // 9: eventtag.EventTagService.FindAllEventTags:input_type -> eventtag.FindAllEventTagsRequest
	11, // 10: eventtag.EventTagService.DeleteEventTag:input_type -> eventtag.DeleteEventTagRequest
	2,  // 11: eventtag.EventTagService.CreateEventTag:output_type -> eventtag.CreateEventTagResponse
	4,  // 12: eventtag.EventTagService.FindByEventAndTagID:output_type -> eventtag.FindByEventAndTagIDResponse
	6,  // 13: eventtag.EventTagService.FindByEventID:output_type -> eventtag.FindByEventIDResponse
	8,  // 14: eventtag.EventTagService.FindByTagID:output_type -> eventtag.FindByTagIDResponse
	10, // 15: eventtag.EventTagService.FindAllEventTags:output_type -> eventtag.FindAllEventTagsResponse
	12, // 16: eventtag.EventTagService.DeleteEventTag:output_type -> eventtag.DeleteEventTagResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_eventtag_eventtag_proto_init() }
func file_proto_eventtag_eventtag_proto_init() {
	if File_proto_eventtag_eventtag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_eventtag_eventtag_proto_rawDesc), len(file_proto_eventtag_eventtag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_eventtag_eventtag_proto_goTypes,
		DependencyIndexes: file_proto_eventtag_eventtag_proto_depIdxs,
		MessageInfos:      file_proto_eventtag_eventtag_proto_msgTypes,
	}.Build()
	File_proto_eventtag_eventtag_proto = out.File
	file_proto_eventtag_eventtag_proto_goTypes = nil
	file_proto_eventtag_eventtag_proto_depIdxs = nil
}
