// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/savedevent/savedevent.proto

package savedevent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SavedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       int32                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavedEvent) Reset() {
	*x = SavedEvent{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedEvent) ProtoMessage() {}

func (x *SavedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedEvent.ProtoReflect.Descriptor instead.
func (*SavedEvent) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{0}
}

func (x *SavedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SavedEvent) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *SavedEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SaveEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       int32                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveEventRequest) Reset() {
	*x = SaveEventRequest{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveEventRequest) ProtoMessage() {}

func (x *SaveEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveEventRequest.ProtoReflect.Descriptor instead.
func (*SaveEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{1}
}

func (x *SaveEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveEventRequest) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type SaveEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavedEvent    *SavedEvent            `protobuf:"bytes,1,opt,name=saved_event,json=savedEvent,proto3" json:"saved_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveEventResponse) Reset() {
	*x = SaveEventResponse{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveEventResponse) ProtoMessage() {}

func (x *SaveEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveEventResponse.ProtoReflect.Descriptor instead.
func (*SaveEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{2}
}

func (x *SaveEventResponse) GetSavedEvent() *SavedEvent {
	if x != nil {
		return x.SavedEvent
	}
	return nil
}

type FindSavedEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       int32                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSavedEventRequest) Reset() {
	*x = FindSavedEventRequest{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSavedEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSavedEventRequest) ProtoMessage() {}

func (x *FindSavedEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSavedEventRequest.ProtoReflect.Descriptor instead.
func (*FindSavedEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{3}
}

func (x *FindSavedEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindSavedEventRequest) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type FindSavedEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavedEvent    *SavedEvent            `protobuf:"bytes,1,opt,name=saved_event,json=savedEvent,proto3" json:"saved_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSavedEventResponse) Reset() {
	*x = FindSavedEventResponse{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSavedEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSavedEventResponse) ProtoMessage() {}

func (x *FindSavedEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSavedEventResponse.ProtoReflect.Descriptor instead.
func (*FindSavedEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{4}
}

func (x *FindSavedEventResponse) GetSavedEvent() *SavedEvent {
	if x != nil {
		return x.SavedEvent
	}
	return nil
}

type FindAllByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByUserRequest) Reset() {
	*x = FindAllByUserRequest{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByUserRequest) ProtoMessage() {}

func (x *FindAllByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByUserRequest.ProtoReflect.Descriptor instead.
func (*FindAllByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindAllByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavedEvents   []*SavedEvent          `protobuf:"bytes,1,rep,name=saved_events,json=savedEvents,proto3" json:"saved_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByUserResponse) Reset() {
	*x = FindAllByUserResponse{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByUserResponse) ProtoMessage() {}

func (x *FindAllByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByUserResponse.ProtoReflect.Descriptor instead.
func (*FindAllByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllByUserResponse) GetSavedEvents() []*SavedEvent {
	if x != nil {
		return x.SavedEvents
	}
	return nil
}

type FindAllByEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int32                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByEventRequest) Reset() {
	*x = FindAllByEventRequest{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByEventRequest) ProtoMessage() {}

func (x *FindAllByEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByEventRequest.ProtoReflect.Descriptor instead.
func (*FindAllByEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllByEventRequest) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type FindAllByEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavedEvents   []*SavedEvent          `protobuf:"bytes,1,rep,name=saved_events,json=savedEvents,proto3" json:"saved_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByEventResponse) Reset() {
	*x = FindAllByEventResponse{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByEventResponse) ProtoMessage() {}

func (x *FindAllByEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByEventResponse.ProtoReflect.Descriptor instead.
func (*FindAllByEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{8}
}

func (x *FindAllByEventResponse) GetSavedEvents() []*SavedEvent {
	if x != nil {
		return x.SavedEvents
	}
	return nil
}

type DeleteSavedEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       int32                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSavedEventRequest) Reset() {
	*x = DeleteSavedEventRequest{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSavedEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSavedEventRequest) ProtoMessage() {}

func (x *DeleteSavedEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSavedEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteSavedEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSavedEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteSavedEventRequest) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type DeleteSavedEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSavedEventResponse) Reset() {
	*x = DeleteSavedEventResponse{}
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSavedEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSavedEventResponse) ProtoMessage() {}

func (x *DeleteSavedEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_savedevent_savedevent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSavedEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteSavedEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_savedevent_savedevent_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSavedEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_savedevent_savedevent_proto protoreflect.FileDescriptor

const file_proto_savedevent_savedevent_proto_rawDesc = "" +
	"\n" +
	"!proto/savedevent/savedevent.proto\x12\n" +
	"savedevent\"_\n" +
	"\n" +
	"SavedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x05R\aeventId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"F\n" +
	"\x10SaveEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x05R\aeventId\"L\n" +
	"\x11SaveEventResponse\x127\n" +
	"\vsaved_event\x18\x01 \x01(\v2\x16.savedevent.SavedEventR\n" +
	"savedEvent\"K\n" +
	"\x15FindSavedEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x05R\aeventId\"Q\n" +
	"\x16FindSavedEventResponse\x127\n" +
	"\vsaved_event\x18\x01 \x01(\v2\x16.savedevent.SavedEventR\n" +
	"savedEvent\"/\n" +
	"\x14FindAllByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x15FindAllByUserResponse\x129\n" +
	"\fsaved_events\x18\x01 \x03(\v2\x16.savedevent.SavedEventR\vsavedEvents\"2\n" +
	"\x15FindAllByEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x05R\aeventId\"S\n" +
	"\x16FindAllByEventResponse\x129\n" +
	"\fsaved_events\x18\x01 \x03(\v2\x16.savedevent.SavedEventR\vsavedEvents\"M\n" +
	"\x17DeleteSavedEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x05R\aeventId\"4\n" +
	"\x18DeleteSavedEventResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc4\x03\n" +
	"\x11SavedEventService\x12H\n" +
	"\tSaveEvent\x12\x1c.savedevent.SaveEventRequest\x1a\x1d.savedevent.SaveEventResponse\x12W\n" +
	"\x0eFindSavedEvent\x12!.savedevent.FindSavedEventRequest\x1a\".savedevent.FindSavedEventResponse\x12T\n" +
	"\rFindAllByUser\x12 .savedevent.FindAllByUserRequest\x1a!.savedevent.FindAllByUserResponse\x12W\n" +
	"\x0eFindAllByEvent\x12!.savedevent.FindAllByEventRequest\x1a\".savedevent.FindAllByEventResponse\x12]\n" +
	"\x10DeleteSavedEvent\x12#.savedevent.DeleteSavedEventRequest\x1a$.savedevent.DeleteSavedEventResponseB\x12Z\x10proto/savedeventb\x06proto3"

var (
	file_proto_savedevent_savedevent_proto_rawDescOnce sync.Once
	file_proto_savedevent_savedevent_proto_rawDescData []byte
)

func file_proto_savedevent_savedevent_proto_rawDescGZIP() []byte {
	file_proto_savedevent_savedevent_proto_rawDescOnce.Do(func() {
		file_proto_savedevent_savedevent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_savedevent_savedevent_proto_rawDesc), len(file_proto_savedevent_savedevent_proto_rawDesc)))
	})
	return file_proto_savedevent_savedevent_proto_rawDescData
}

var file_proto_savedevent_savedevent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_savedevent_savedevent_proto_goTypes = []any{
	(*SavedEvent)(nil),               // 0: savedevent.SavedEvent
	(*SaveEventRequest)(nil),         // 1: savedevent.SaveEventRequest
	(*SaveEventResponse)(nil),        // 2: savedevent.SaveEventResponse
	(*FindSavedEventRequest)(nil),    // 3: savedevent.FindSavedEventRequest
	(*FindSavedEventResponse)(nil),   // 4: savedevent.FindSavedEventResponse
	(*FindAllByUserRequest)(nil),     // 5: savedevent.FindAllByUserRequest
	(*FindAllByUserResponse)(nil),    // 6: savedevent.FindAllByUserResponse
	(*FindAllByEventRequest)(nil),    // 7: savedevent.FindAllByEventRequest
	(*FindAllByEventResponse)(nil),   // 8: savedevent.FindAllByEventResponse
	(*DeleteSavedEventRequest)(nil),  // 9: savedevent.DeleteSavedEventRequest
	(*DeleteSavedEventResponse)(nil), // 10: savedevent.DeleteSavedEventResponse
}
var file_proto_savedevent_savedevent_proto_depIdxs = []int32{
	0,  // 0: savedevent.SaveEventResponse.saved_event:type_name -> savedevent.SavedEvent
	0,  // 1: savedevent.FindSavedEventResponse.saved_event:type_name -> savedevent.SavedEvent
	0,  // 2: savedevent.FindAllByUserResponse.saved_events:type_name -> savedevent.SavedEvent
	0,  // 3: savedevent.FindAllByEventResponse.saved_events:type_name -> savedevent.SavedEvent
	1,  // 4: savedevent.SavedEventService.SaveEvent:input_type -> savedevent.SaveEventRequest
	3,  // 5: savedevent.SavedEventService.FindSavedEvent:input_type -> savedevent.FindSavedEventRequest
	5,  // 6: savedevent.SavedEventService.FindAllByUser:input_type -> savedevent.FindAllByUserRequest
	7,  // 7: savedevent.SavedEventService.FindAllByEvent:input_type -> savedevent.FindAllByEventRequest
	9,  // 8: savedevent.SavedEventService.DeleteSavedEvent:input_type -> savedevent.DeleteSavedEventRequest
	2,  // 9: savedevent.SavedEventService.SaveEvent:output_type -> savedevent.SaveEventResponse
	4,  // 10: savedevent.SavedEventService.FindSavedEvent:output_type -> savedevent.FindSavedEventResponse
	6,  // 11: savedevent.SavedEventService.FindAllByUser:output_type -> savedevent.FindAllByUserResponse
	8,  // 12: savedevent.SavedEventService.FindAllByEvent:output_type -> savedevent.FindAllByEventResponse
	10, // 13: savedevent.SavedEventService.DeleteSavedEvent:output_type -> savedevent.DeleteSavedEventResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_savedevent_savedevent_proto_init() }
func file_proto_savedevent_savedevent_proto_init() {
	if File_proto_savedevent_savedevent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_savedevent_savedevent_proto_rawDesc), len(file_proto_savedevent_savedevent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_savedevent_savedevent_proto_goTypes,
		DependencyIndexes: file_proto_savedevent_savedevent_proto_depIdxs,
		MessageInfos:      file_proto_savedevent_savedevent_proto_msgTypes,
	}.Build()
	File_proto_savedevent_savedevent_proto = out.File
	file_proto_savedevent_savedevent_proto_goTypes = nil
	file_proto_savedevent_savedevent_proto_depIdxs = nil
}
