// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: proto/event/event.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_event_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Event struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventName        string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventDescription string                 `protobuf:"bytes,3,opt,name=event_description,json=eventDescription,proto3" json:"event_description,omitempty"`
	StartAt          string                 `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt            string                 `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	MainImageUrl     string                 `protobuf:"bytes,6,opt,name=main_image_url,json=mainImageUrl,proto3" json:"main_image_url,omitempty"`
	RegisterStartDt  string                 `protobuf:"bytes,7,opt,name=register_start_dt,json=registerStartDt,proto3" json:"register_start_dt,omitempty"`
	RegisterCloseDt  string                 `protobuf:"bytes,8,opt,name=register_close_dt,json=registerCloseDt,proto3" json:"register_close_dt,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_event_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Event) GetEventDescription() string {
	if x != nil {
		return x.EventDescription
	}
	return ""
}

func (x *Event) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *Event) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *Event) GetMainImageUrl() string {
	if x != nil {
		return x.MainImageUrl
	}
	return ""
}

func (x *Event) GetRegisterStartDt() string {
	if x != nil {
		return x.RegisterStartDt
	}
	return ""
}

func (x *Event) GetRegisterCloseDt() string {
	if x != nil {
		return x.RegisterCloseDt
	}
	return ""
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Event) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateEventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventName        string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventDescription string                 `protobuf:"bytes,2,opt,name=event_description,json=eventDescription,proto3" json:"event_description,omitempty"`
	StartAt          string                 `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt            string                 `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	MainImageUrl     string                 `protobuf:"bytes,5,opt,name=main_image_url,json=mainImageUrl,proto3" json:"main_image_url,omitempty"`
	RegisterStartDt  string                 `protobuf:"bytes,6,opt,name=register_start_dt,json=registerStartDt,proto3" json:"register_start_dt,omitempty"`
	RegisterCloseDt  string                 `protobuf:"bytes,7,opt,name=register_close_dt,json=registerCloseDt,proto3" json:"register_close_dt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_proto_event_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *CreateEventRequest) GetEventDescription() string {
	if x != nil {
		return x.EventDescription
	}
	return ""
}

func (x *CreateEventRequest) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *CreateEventRequest) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *CreateEventRequest) GetMainImageUrl() string {
	if x != nil {
		return x.MainImageUrl
	}
	return ""
}

func (x *CreateEventRequest) GetRegisterStartDt() string {
	if x != nil {
		return x.RegisterStartDt
	}
	return ""
}

func (x *CreateEventRequest) GetRegisterCloseDt() string {
	if x != nil {
		return x.RegisterCloseDt
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_proto_event_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type FindEventByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEventByIDRequest) Reset() {
	*x = FindEventByIDRequest{}
	mi := &file_proto_event_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEventByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEventByIDRequest) ProtoMessage() {}

func (x *FindEventByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEventByIDRequest.ProtoReflect.Descriptor instead.
func (*FindEventByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{4}
}

func (x *FindEventByIDRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindEventByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEventByIDResponse) Reset() {
	*x = FindEventByIDResponse{}
	mi := &file_proto_event_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEventByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEventByIDResponse) ProtoMessage() {}

func (x *FindEventByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEventByIDResponse.ProtoReflect.Descriptor instead.
func (*FindEventByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{5}
}

func (x *FindEventByIDResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type FindAllEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEventsRequest) Reset() {
	*x = FindAllEventsRequest{}
	mi := &file_proto_event_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEventsRequest) ProtoMessage() {}

func (x *FindAllEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEventsRequest.ProtoReflect.Descriptor instead.
func (*FindAllEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{6}
}

type FindAllEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEventsResponse) Reset() {
	*x = FindAllEventsResponse{}
	mi := &file_proto_event_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEventsResponse) ProtoMessage() {}

func (x *FindAllEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEventsResponse.ProtoReflect.Descriptor instead.
func (*FindAllEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type PatchEventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventName        string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventDescription string                 `protobuf:"bytes,3,opt,name=event_description,json=eventDescription,proto3" json:"event_description,omitempty"`
	StartAt          string                 `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt            string                 `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	MainImageUrl     string                 `protobuf:"bytes,6,opt,name=main_image_url,json=mainImageUrl,proto3" json:"main_image_url,omitempty"`
	RegisterStartDt  string                 `protobuf:"bytes,7,opt,name=register_start_dt,json=registerStartDt,proto3" json:"register_start_dt,omitempty"`
	RegisterCloseDt  string                 `protobuf:"bytes,8,opt,name=register_close_dt,json=registerCloseDt,proto3" json:"register_close_dt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PatchEventRequest) Reset() {
	*x = PatchEventRequest{}
	mi := &file_proto_event_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchEventRequest) ProtoMessage() {}

func (x *PatchEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchEventRequest.ProtoReflect.Descriptor instead.
func (*PatchEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{8}
}

func (x *PatchEventRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *PatchEventRequest) GetEventDescription() string {
	if x != nil {
		return x.EventDescription
	}
	return ""
}

func (x *PatchEventRequest) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *PatchEventRequest) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *PatchEventRequest) GetMainImageUrl() string {
	if x != nil {
		return x.MainImageUrl
	}
	return ""
}

func (x *PatchEventRequest) GetRegisterStartDt() string {
	if x != nil {
		return x.RegisterStartDt
	}
	return ""
}

func (x *PatchEventRequest) GetRegisterCloseDt() string {
	if x != nil {
		return x.RegisterCloseDt
	}
	return ""
}

type PatchEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchEventResponse) Reset() {
	*x = PatchEventResponse{}
	mi := &file_proto_event_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchEventResponse) ProtoMessage() {}

func (x *PatchEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchEventResponse.ProtoReflect.Descriptor instead.
func (*PatchEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{9}
}

func (x *PatchEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_proto_event_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteEventRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_proto_event_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_event_event_proto protoreflect.FileDescriptor

const file_proto_event_event_proto_rawDesc = "" +
	"\n" +
	"\x17proto/event/event.proto\x12\x05event\"-\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"\xd1\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12+\n" +
	"\x11event_description\x18\x03 \x01(\tR\x10eventDescription\x12\x19\n" +
	"\bstart_at\x18\x04 \x01(\tR\astartAt\x12\x15\n" +
	"\x06end_at\x18\x05 \x01(\tR\x05endAt\x12$\n" +
	"\x0emain_image_url\x18\x06 \x01(\tR\fmainImageUrl\x12*\n" +
	"\x11register_start_dt\x18\a \x01(\tR\x0fregisterStartDt\x12*\n" +
	"\x11register_close_dt\x18\b \x01(\tR\x0fregisterCloseDt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\x90\x02\n" +
	"\x12CreateEventRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12+\n" +
	"\x11event_description\x18\x02 \x01(\tR\x10eventDescription\x12\x19\n" +
	"\bstart_at\x18\x03 \x01(\tR\astartAt\x12\x15\n" +
	"\x06end_at\x18\x04 \x01(\tR\x05endAt\x12$\n" +
	"\x0emain_image_url\x18\x05 \x01(\tR\fmainImageUrl\x12*\n" +
	"\x11register_start_dt\x18\x06 \x01(\tR\x0fregisterStartDt\x12*\n" +
	"\x11register_close_dt\x18\a \x01(\tR\x0fregisterCloseDt\"9\n" +
	"\x13CreateEventResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"&\n" +
	"\x14FindEventByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\";\n" +
	"\x15FindEventByIDResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"\x16\n" +
	"\x14FindAllEventsRequest\"=\n" +
	"\x15FindAllEventsResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\"\x9f\x02\n" +
	"\x11PatchEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12+\n" +
	"\x11event_description\x18\x03 \x01(\tR\x10eventDescription\x12\x19\n" +
	"\bstart_at\x18\x04 \x01(\tR\astartAt\x12\x15\n" +
	"\x06end_at\x18\x05 \x01(\tR\x05endAt\x12$\n" +
	"\x0emain_image_url\x18\x06 \x01(\tR\fmainImageUrl\x12*\n" +
	"\x11register_start_dt\x18\a \x01(\tR\x0fregisterStartDt\x12*\n" +
	"\x11register_close_dt\x18\b \x01(\tR\x0fregisterCloseDt\"8\n" +
	"\x12PatchEventResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"/\n" +
	"\x13DeleteEventResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf5\x02\n" +
	"\fEventService\x12D\n" +
	"\vCreateEvent\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\x12J\n" +
	"\rFindEventByID\x12\x1b.event.FindEventByIDRequest\x1a\x1c.event.FindEventByIDResponse\x12J\n" +
	"\rFindAllEvents\x12\x1b.event.FindAllEventsRequest\x1a\x1c.event.FindAllEventsResponse\x12A\n" +
	"\n" +
	"PatchEvent\x12\x18.event.PatchEventRequest\x1a\x19.event.PatchEventResponse\x12D\n" +
	"\vDeleteEvent\x12\x19.event.DeleteEventRequest\x1a\x1a.event.DeleteEventResponseB.Z,github.com/MingPV/EventService/proto/eventpbb\x06proto3"

var (
	file_proto_event_event_proto_rawDescOnce sync.Once
	file_proto_event_event_proto_rawDescData []byte
)

func file_proto_event_event_proto_rawDescGZIP() []byte {
	file_proto_event_event_proto_rawDescOnce.Do(func() {
		file_proto_event_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_event_proto_rawDesc), len(file_proto_event_event_proto_rawDesc)))
	})
	return file_proto_event_event_proto_rawDescData
}

var file_proto_event_event_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_event_event_proto_goTypes = []any{
	(*Order)(nil),                 // 0: event.Order
	(*Event)(nil),                 // 1: event.Event
	(*CreateEventRequest)(nil),    // 2: event.CreateEventRequest
	(*CreateEventResponse)(nil),   // 3: event.CreateEventResponse
	(*FindEventByIDRequest)(nil),  // 4: event.FindEventByIDRequest
	(*FindEventByIDResponse)(nil), // 5: event.FindEventByIDResponse
	(*FindAllEventsRequest)(nil),  // 6: event.FindAllEventsRequest
	(*FindAllEventsResponse)(nil), // 7: event.FindAllEventsResponse
	(*PatchEventRequest)(nil),     // 8: event.PatchEventRequest
	(*PatchEventResponse)(nil),    // 9: event.PatchEventResponse
	(*DeleteEventRequest)(nil),    // 10: event.DeleteEventRequest
	(*DeleteEventResponse)(nil),   // 11: event.DeleteEventResponse
}
var file_proto_event_event_proto_depIdxs = []int32{
	1,  // 0: event.CreateEventResponse.event:type_name -> event.Event
	1,  // 1: event.FindEventByIDResponse.event:type_name -> event.Event
	1,  // 2: event.FindAllEventsResponse.events:type_name -> event.Event
	1,  // 3: event.PatchEventResponse.event:type_name -> event.Event
	2,  // 4: event.EventService.CreateEvent:input_type -> event.CreateEventRequest
	4,  // 5: event.EventService.FindEventByID:input_type -> event.FindEventByIDRequest
	6,  // 6: event.EventService.FindAllEvents:input_type -> event.FindAllEventsRequest
	8,  // 7: event.EventService.PatchEvent:input_type -> event.PatchEventRequest
	10, // 8: event.EventService.DeleteEvent:input_type -> event.DeleteEventRequest
	3,  // 9: event.EventService.CreateEvent:output_type -> event.CreateEventResponse
	5,  // 10: event.EventService.FindEventByID:output_type -> event.FindEventByIDResponse
	7,  // 11: event.EventService.FindAllEvents:output_type -> event.FindAllEventsResponse
	9,  // 12: event.EventService.PatchEvent:output_type -> event.PatchEventResponse
	11, // 13: event.EventService.DeleteEvent:output_type -> event.DeleteEventResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_event_event_proto_init() }
func file_proto_event_event_proto_init() {
	if File_proto_event_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_event_proto_rawDesc), len(file_proto_event_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_event_event_proto_goTypes,
		DependencyIndexes: file_proto_event_event_proto_depIdxs,
		MessageInfos:      file_proto_event_event_proto_msgTypes,
	}.Build()
	File_proto_event_event_proto = out.File
	file_proto_event_event_proto_goTypes = nil
	file_proto_event_event_proto_depIdxs = nil
}
