// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: proto/event_tag/event_tag.proto

package event_tag_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId         uint32                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTag) Reset() {
	*x = EventTag{}
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTag) ProtoMessage() {}

func (x *EventTag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTag.ProtoReflect.Descriptor instead.
func (*EventTag) Descriptor() ([]byte, []int) {
	return file_proto_event_tag_event_tag_proto_rawDescGZIP(), []int{0}
}

func (x *EventTag) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventTag) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *EventTag) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EventTag) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateEventTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId         uint32                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventTagRequest) Reset() {
	*x = CreateEventTagRequest{}
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventTagRequest) ProtoMessage() {}

func (x *CreateEventTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventTagRequest.ProtoReflect.Descriptor instead.
func (*CreateEventTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_tag_event_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventTagRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateEventTagRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type CreateEventTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTag      *EventTag              `protobuf:"bytes,1,opt,name=event_tag,json=eventTag,proto3" json:"event_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventTagResponse) Reset() {
	*x = CreateEventTagResponse{}
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventTagResponse) ProtoMessage() {}

func (x *CreateEventTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventTagResponse.ProtoReflect.Descriptor instead.
func (*CreateEventTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_tag_event_tag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventTagResponse) GetEventTag() *EventTag {
	if x != nil {
		return x.EventTag
	}
	return nil
}

type FindEventTagByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId         uint32                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEventTagByIDRequest) Reset() {
	*x = FindEventTagByIDRequest{}
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEventTagByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEventTagByIDRequest) ProtoMessage() {}

func (x *FindEventTagByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEventTagByIDRequest.ProtoReflect.Descriptor instead.
func (*FindEventTagByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_tag_event_tag_proto_rawDescGZIP(), []int{3}
}

func (x *FindEventTagByIDRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *FindEventTagByIDRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type FindEventTagByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTag      *EventTag              `protobuf:"bytes,1,opt,name=event_tag,json=eventTag,proto3" json:"event_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEventTagByIDResponse) Reset() {
	*x = FindEventTagByIDResponse{}
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEventTagByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEventTagByIDResponse) ProtoMessage() {}

func (x *FindEventTagByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEventTagByIDResponse.ProtoReflect.Descriptor instead.
func (*FindEventTagByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_tag_event_tag_proto_rawDescGZIP(), []int{4}
}

func (x *FindEventTagByIDResponse) GetEventTag() *EventTag {
	if x != nil {
		return x.EventTag
	}
	return nil
}

type FindAllEventTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEventTagsRequest) Reset() {
	*x = FindAllEventTagsRequest{}
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEventTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEventTagsRequest) ProtoMessage() {}

func (x *FindAllEventTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEventTagsRequest.ProtoReflect.Descriptor instead.
func (*FindAllEventTagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_tag_event_tag_proto_rawDescGZIP(), []int{5}
}

type FindAllEventTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTags     []*EventTag            `protobuf:"bytes,1,rep,name=event_tags,json=eventTags,proto3" json:"event_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllEventTagsResponse) Reset() {
	*x = FindAllEventTagsResponse{}
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllEventTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllEventTagsResponse) ProtoMessage() {}

func (x *FindAllEventTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllEventTagsResponse.ProtoReflect.Descriptor instead.
func (*FindAllEventTagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_tag_event_tag_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllEventTagsResponse) GetEventTags() []*EventTag {
	if x != nil {
		return x.EventTags
	}
	return nil
}

type DeleteEventTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TagId         uint32                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventTagRequest) Reset() {
	*x = DeleteEventTagRequest{}
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventTagRequest) ProtoMessage() {}

func (x *DeleteEventTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_tag_event_tag_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEventTagRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *DeleteEventTagRequest) GetTagId() uint32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type DeleteEventTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventTagResponse) Reset() {
	*x = DeleteEventTagResponse{}
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventTagResponse) ProtoMessage() {}

func (x *DeleteEventTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_tag_event_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_tag_event_tag_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEventTagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_event_tag_event_tag_proto protoreflect.FileDescriptor

const file_proto_event_tag_event_tag_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/event_tag/event_tag.proto\x12\tevent_tag\"z\n" +
	"\bEventTag\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\rR\x05tagId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"I\n" +
	"\x15CreateEventTagRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\rR\x05tagId\"J\n" +
	"\x16CreateEventTagResponse\x120\n" +
	"\tevent_tag\x18\x01 \x01(\v2\x13.event_tag.EventTagR\beventTag\"K\n" +
	"\x17FindEventTagByIDRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\rR\x05tagId\"L\n" +
	"\x18FindEventTagByIDResponse\x120\n" +
	"\tevent_tag\x18\x01 \x01(\v2\x13.event_tag.EventTagR\beventTag\"\x19\n" +
	"\x17FindAllEventTagsRequest\"N\n" +
	"\x18FindAllEventTagsResponse\x122\n" +
	"\n" +
	"event_tags\x18\x01 \x03(\v2\x13.event_tag.EventTagR\teventTags\"I\n" +
	"\x15DeleteEventTagRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\rR\x05tagId\"2\n" +
	"\x16DeleteEventTagResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf9\x02\n" +
	"\x0fEventTagService\x12U\n" +
	"\x0eCreateEventTag\x12 .event_tag.CreateEventTagRequest\x1a!.event_tag.CreateEventTagResponse\x12[\n" +
	"\x10FindEventTagByID\x12\".event_tag.FindEventTagByIDRequest\x1a#.event_tag.FindEventTagByIDResponse\x12[\n" +
	"\x10FindAllEventTags\x12\".event_tag.FindAllEventTagsRequest\x1a#.event_tag.FindAllEventTagsResponse\x12U\n" +
	"\x0eDeleteEventTag\x12 .event_tag.DeleteEventTagRequest\x1a!.event_tag.DeleteEventTagResponseB3Z1github.com/MingPV/EventService/proto/event_tag_pbb\x06proto3"

var (
	file_proto_event_tag_event_tag_proto_rawDescOnce sync.Once
	file_proto_event_tag_event_tag_proto_rawDescData []byte
)

func file_proto_event_tag_event_tag_proto_rawDescGZIP() []byte {
	file_proto_event_tag_event_tag_proto_rawDescOnce.Do(func() {
		file_proto_event_tag_event_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_tag_event_tag_proto_rawDesc), len(file_proto_event_tag_event_tag_proto_rawDesc)))
	})
	return file_proto_event_tag_event_tag_proto_rawDescData
}

var file_proto_event_tag_event_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_event_tag_event_tag_proto_goTypes = []any{
	(*EventTag)(nil),                 // 0: event_tag.EventTag
	(*CreateEventTagRequest)(nil),    // 1: event_tag.CreateEventTagRequest
	(*CreateEventTagResponse)(nil),   // 2: event_tag.CreateEventTagResponse
	(*FindEventTagByIDRequest)(nil),  // 3: event_tag.FindEventTagByIDRequest
	(*FindEventTagByIDResponse)(nil), // 4: event_tag.FindEventTagByIDResponse
	(*FindAllEventTagsRequest)(nil),  // 5: event_tag.FindAllEventTagsRequest
	(*FindAllEventTagsResponse)(nil), // 6: event_tag.FindAllEventTagsResponse
	(*DeleteEventTagRequest)(nil),    // 7: event_tag.DeleteEventTagRequest
	(*DeleteEventTagResponse)(nil),   // 8: event_tag.DeleteEventTagResponse
}
var file_proto_event_tag_event_tag_proto_depIdxs = []int32{
	0, // 0: event_tag.CreateEventTagResponse.event_tag:type_name -> event_tag.EventTag
	0, // 1: event_tag.FindEventTagByIDResponse.event_tag:type_name -> event_tag.EventTag
	0, // 2: event_tag.FindAllEventTagsResponse.event_tags:type_name -> event_tag.EventTag
	1, // 3: event_tag.EventTagService.CreateEventTag:input_type -> event_tag.CreateEventTagRequest
	3, // 4: event_tag.EventTagService.FindEventTagByID:input_type -> event_tag.FindEventTagByIDRequest
	5, // 5: event_tag.EventTagService.FindAllEventTags:input_type -> event_tag.FindAllEventTagsRequest
	7, // 6: event_tag.EventTagService.DeleteEventTag:input_type -> event_tag.DeleteEventTagRequest
	2, // 7: event_tag.EventTagService.CreateEventTag:output_type -> event_tag.CreateEventTagResponse
	4, // 8: event_tag.EventTagService.FindEventTagByID:output_type -> event_tag.FindEventTagByIDResponse
	6, // 9: event_tag.EventTagService.FindAllEventTags:output_type -> event_tag.FindAllEventTagsResponse
	8, // 10: event_tag.EventTagService.DeleteEventTag:output_type -> event_tag.DeleteEventTagResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_event_tag_event_tag_proto_init() }
func file_proto_event_tag_event_tag_proto_init() {
	if File_proto_event_tag_event_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_tag_event_tag_proto_rawDesc), len(file_proto_event_tag_event_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_event_tag_event_tag_proto_goTypes,
		DependencyIndexes: file_proto_event_tag_event_tag_proto_depIdxs,
		MessageInfos:      file_proto_event_tag_event_tag_proto_msgTypes,
	}.Build()
	File_proto_event_tag_event_tag_proto = out.File
	file_proto_event_tag_event_tag_proto_goTypes = nil
	file_proto_event_tag_event_tag_proto_depIdxs = nil
}
